[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NEXT_PUBLIC_SUPABASE_URL = "https://jzkouytzmgjrqvgercav.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6a291eXR6bWdqcnF2Z2VyY2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTc0MzA0MDAsImV4cCI6MjAzMzAwNjQwMH0.Wd0jXKYQQM9wQAVzMGDZbA-HQooXk6c3G2O5JMqDhNE"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6a291eXR6bWdqcnF2Z2VyY2F2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNzQzMDQwMCwiZXhwIjoyMDMzMDA2NDAwfQ.Wd0jXKYQQM9wQAVzMGDZbA-HQooXk6c3G2O5JMqDhNE"
  GITHUB_CLIENT_ID = "Ov23litAUoXG21W1xPRN"
  GITHUB_CLIENT_SECRET = "1bc024d8d413c13ec465268a54db451f9040dd29"
  NEXT_PUBLIC_SITE_URL = "https://nexusworks.in"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200