# Generated by Django 5.2.4 on 2025-07-17 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ai_complexity_score',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ai_estimated_duration_days',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ai_recommended_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_freelancer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='complexity_level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hourly_rate_max',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started_at',
        ),
        migrations.AddField(
            model_name='project',
            name='ai_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='senior_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senior_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='timeline_estimate',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience_level_required',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('expert', 'Expert')], default='mid', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Analyzing'), ('proposal_review', 'Proposal Review'), ('team_assembly', 'Team Assembly'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='analyzing', max_length=20),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('estimated_hours', models.IntegerField()),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, to='projects.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['project', 'priority'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectBid',
        ),
        migrations.DeleteModel(
            name='ProjectMilestone',
        ),
    ]
