# Generated by Django 5.2.4 on 2025-07-17 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_projectmilestone_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_timeline', models.DurationField()),
                ('original_task_breakdown', models.JSONField(default=dict)),
                ('original_sla_terms', models.JSONField(default=dict)),
                ('current_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_timeline', models.DurationField()),
                ('current_task_breakdown', models.JSONField(default=dict)),
                ('current_sla_terms', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('senior_review', 'Senior Developer Review'), ('client_review', 'Client Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('senior_developer_approved', models.BooleanField(default=False)),
                ('senior_developer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved', models.BooleanField(default=False)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_proposals', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='projects.project')),
            ],
            options={
                'db_table': 'project_proposals',
            },
        ),
        migrations.CreateModel(
            name='ProposalModification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modification_type', models.CharField(choices=[('budget_change', 'Budget Change'), ('timeline_change', 'Timeline Change'), ('task_modification', 'Task Modification'), ('sla_change', 'SLA Change'), ('scope_change', 'Scope Change')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField()),
                ('new_value', models.JSONField()),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_modifications', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='projects.projectproposal')),
            ],
            options={
                'db_table': 'proposal_modifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeniorDeveloperAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experience_score', models.FloatField()),
                ('reputation_score', models.FloatField()),
                ('skill_match_score', models.FloatField()),
                ('leadership_score', models.FloatField()),
                ('total_score', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_assignment', to='projects.project')),
                ('senior_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senior_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'senior_developer_assignments',
            },
        ),
    ]
