# Generated by Django 5.2.4 on 2025-07-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_dynamicpricing_resourceallocation_teaminvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('qa_review', 'QA Review'), ('client_review', 'Client Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('qa_review', 'QA Review'), ('client_review', 'Client Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
