# Generated by Django 5.2.4 on 2025-07-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('project_update', 'Project Update'), ('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_qa_review', 'Task QA Review'), ('task_client_approval', 'Task Client Approval'), ('task_approved', 'Task Approved'), ('task_qa_rejected', 'Task QA Rejected'), ('task_client_rejected', 'Task Client Rejected'), ('milestone_completed', 'Milestone Completed'), ('payment_received', 'Payment Received'), ('milestone_reached', 'Milestone Reached'), ('review_request', 'Review Request'), ('system_announcement', 'System Announcement')], max_length=30),
        ),
    ]
