# Generated by Django 5.2.4 on 2025-07-17 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('vector_score', models.FloatField()),
                ('graph_score', models.FloatField()),
                ('availability_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_matches', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_matches', to='projects.task')),
            ],
            options={
                'db_table': 'developer_matches',
                'ordering': ['-match_score'],
                'unique_together': {('task', 'developer')},
            },
        ),
    ]
