# Generated by Django 5.2.4 on 2025-07-17 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('projects', '0003_remove_projectmilestone_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('cache_data', models.JSONField()),
                ('search_type', models.CharField(max_length=20)),
                ('parameters_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'matching_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('developer_search', 'Developer Search'), ('project_search', 'Project Search'), ('batch_match', 'Batch Match'), ('feedback', 'Feedback')], max_length=20)),
                ('match_count', models.IntegerField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('search_parameters', models.JSONField(blank=True, default=dict)),
                ('feedback_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_analytics', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_analytics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MatchingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_experience_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal')], max_length=20, null=True)),
                ('max_experience_level', models.CharField(blank=True, choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior'), ('lead', 'Lead'), ('principal', 'Principal')], max_length=20, null=True)),
                ('preferred_skills', models.JSONField(blank=True, default=list)),
                ('excluded_skills', models.JSONField(blank=True, default=list)),
                ('preferred_timezones', models.JSONField(blank=True, default=list)),
                ('remote_only', models.BooleanField(default=False)),
                ('preferred_project_types', models.JSONField(blank=True, default=list)),
                ('excluded_project_types', models.JSONField(blank=True, default=list)),
                ('skill_weight', models.FloatField(default=0.4)),
                ('experience_weight', models.FloatField(default=0.3)),
                ('availability_weight', models.FloatField(default=0.2)),
                ('reputation_weight', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_preferences',
            },
        ),
    ]
