apiVersion: v1
kind: ConfigMap
metadata:
  name: freelance-platform-config
  namespace: freelance-platform
data:
  # Django settings
  DJANGO_SETTINGS_MODULE: "freelance_platform.settings"
  DEBUG: "False"
  ENVIRONMENT: "production"
  
  # Allowed hosts
  ALLOWED_HOSTS: "api.freelanceplatform.com,freelanceplatform.com,www.freelanceplatform.com"
  
  # CORS settings
  CORS_ALLOWED_ORIGINS: "https://freelanceplatform.com,https://www.freelanceplatform.com"
  CORS_ALLOW_CREDENTIALS: "True"
  
  # Security settings
  SECURE_SSL_REDIRECT: "True"
  SECURE_HSTS_SECONDS: "31536000"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  SECURE_HSTS_PRELOAD: "True"
  SECURE_CONTENT_TYPE_NOSNIFF: "True"
  SECURE_BROWSER_XSS_FILTER: "True"
  X_FRAME_OPTIONS: "DENY"
  SECURE_REFERRER_POLICY: "strict-origin-when-cross-origin"
  
  # Session settings
  SESSION_COOKIE_SECURE: "True"
  SESSION_COOKIE_HTTPONLY: "True"
  SESSION_COOKIE_SAMESITE: "Lax"
  CSRF_COOKIE_SECURE: "True"
  CSRF_COOKIE_HTTPONLY: "True"
  CSRF_COOKIE_SAMESITE: "Lax"
  
  # Database settings
  DB_CONN_MAX_AGE: "300"
  DB_MAX_CONNS: "20"
  DB_MIN_CONNS: "5"
  DB_CONNECT_TIMEOUT: "10"
  DB_SSL_MODE: "require"
  
  # Redis settings
  REDIS_MAX_CONNECTIONS: "50"
  CACHE_TIMEOUT: "300"
  SESSION_TIMEOUT: "86400"
  
  # Celery settings
  CELERY_WORKER_CONCURRENCY: "4"
  
  # File storage
  USE_S3: "True"
  AWS_S3_REGION_NAME: "us-east-1"
  AWS_S3_CUSTOM_DOMAIN: "cdn.freelanceplatform.com"
  
  # Monitoring
  LOG_LEVEL: "INFO"
  ENABLE_PERFORMANCE_MONITORING: "True"
  HEALTH_CHECK_ENABLED: "True"
  HEALTH_CHECK_DATABASE: "True"
  HEALTH_CHECK_CACHE: "True"
  HEALTH_CHECK_EXTERNAL_SERVICES: "True"
  
  # Rate limiting
  RATE_LIMIT_ENABLE: "True"
  RATE_LIMIT_PER_IP: "100"
  RATE_LIMIT_WINDOW: "3600"
  
  # Feature flags
  ENABLE_AI_MATCHING: "True"
  ENABLE_PAYMENT_PROCESSING: "True"
  ENABLE_GITHUB_INTEGRATION: "True"
  ENABLE_LEARNING_PLATFORM: "True"
  ENABLE_COMMUNITY_FEATURES: "True"
  
  # Backup settings
  BACKUP_ENABLED: "True"
  BACKUP_RETENTION_DAYS: "30"
  
  # Application version
  VERSION: "1.0.0"